version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: superapp-postgres
    environment:
      POSTGRES_DB: superapp
      POSTGRES_USER: superapp
      POSTGRES_PASSWORD: superapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: superapp-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
