blank_issues_enabled: false
contact_links:
  - name: Project Discussions
    url: https://github.com/Apatie-codex/discussions
    about: Please use the discussion forum for questions or general conversations.
