name: Feature Request
description: Suggest an idea or enhancement for the project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your interest in improving the project!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a concise summary of the request.
      placeholder: Short description of the feature
    validations:
      required: true
  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: Describe the problem or opportunity this feature addresses.
      placeholder: Explain the motivation behind the request
    validations:
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or approach.
      placeholder: Outline your idea or approach
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add links or drag in any supporting visuals.
      placeholder: Attach or link to screenshots or diagrams
    validations:
      required: false
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define what success looks like for this request.
      placeholder: List acceptance criteria
    validations:
      required: false
