name: superapp
description: Super app scaffold with appointments, marketplace, and services modules.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.3
  dio: ^5.5.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
