name: flutter_app
description: Apatie Codex frontend application scaffolded with Flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^13.1.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  intl: ^0.18.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  generate: true
