name: apatie
description: Apatie Codex frontend application scaffolded with Flutter.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7
  intl: ^0.20.2
  path_provider: ^2.1.5
  flutter_gen: ^5.12.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  flutter_lints: ^6.0.0
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  vm_service: ^14.2.4

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf

  generate: true
