version: "3.9"

services:
  backend:
    env_file: []
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-apatie}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-apatie-insecure-dev-secret-2f3f4c0fb3c7430b8e6a1a9b7d}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,backend}
      DJANGO_ADMIN_URL: ${DJANGO_ADMIN_URL:-admin/}
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-apatie}}
      REDIS_URL: ${REDIS_URL:-redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8080}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost:3000,http://localhost:8080}
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/backend
    ports:
      - "8000:8000"

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
