version: "3.9"

services:
  backend:
    env_file: []
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-apatie}
      POSTGRES_DB: ${POSTGRES_DB:-apatie}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-me}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,backend}
      DJANGO_ADMIN_URL: ${DJANGO_ADMIN_URL:-admin/}
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/apatie}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8080}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost:3000,http://localhost:8080}
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/backend
    ports:
      - "8000:8000"

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
