name: Backend CI

on:
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'backend/**'
      - 'requirements.txt'
      - 'pytest.ini'
      - '.pre-commit-config.yaml'
  pull_request:
    paths:
      - '.github/workflows/backend.yml'
      - 'backend/**'
      - 'requirements.txt'
      - 'pytest.ini'
      - '.pre-commit-config.yaml'

jobs:
  lint-and-test:
    name: Test (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Run pytest
        env:
          DJANGO_SETTINGS_MODULE: core.settings.test
          PYTHONPATH: backend
        run: pytest
