name: Frontend CI

on:
  push:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'

jobs:
  flutter-ci:
    name: Flutter format, analyze & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            frontend/flutter_app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('frontend/flutter_app/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        working-directory: frontend/flutter_app
        run: flutter pub get

      - name: Format check
        working-directory: frontend/flutter_app
        run: flutter format --set-exit-if-changed .

      - name: Analyze
        working-directory: frontend/flutter_app
        run: flutter analyze

      - name: Test
        working-directory: frontend/flutter_app
        run: flutter test
