name: Infrastructure Checks

on:
  push:
    paths:
      - '.github/workflows/infra.yml'
      - 'infra/**'
  pull_request:
    paths:
      - '.github/workflows/infra.yml'
      - 'infra/**'

jobs:
  docker-build:
    name: docker compose build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: docker compose -f infra/docker-compose.yml build
